version: "3.7"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    working_dir: /app
    command: npm run preview
    container_name: vue-app



